add startup message
dgkf/R pull request #161
Opened 2024-07-30 15:40 UTC by sebffischer

I showed the project to a colleague and one thing that confused him was that it was not clear which functions are already available. This is a bit of a cheap solution, I think long term it would be great to maybe list the implemented functions in the website.

2024-07-30 18:55 UTC, dgkf commented
> This is a bit of a cheap solution, I think long term it would be great to maybe list the implemented functions in the website.

Definitely something to consider. I wonder if there's a way to hook into `rustdoc` to include a wasm console to show examples for all the builtin functions.

2024-07-30 19:02 UTC, dgkf requested changes

2024-07-30 19:04 UTC, dgkf commented on src/repl/release.rs
> +pub const AVAILABLE_FUNCTIONS: &str = "You can list all implemented functions via names(parent()).";
Hope you don't mind - just went ahead and made a slight phrasing change.

2024-07-30 19:05 UTC, dgkf requested changes

2024-07-30 19:05 UTC, dgkf commented on src/repl/release.rs
> +pub const AVAILABLE_FUNCTIONS: &str = "\nSee a list of implemented functions using `names(parent())`\n";
```suggestion
pub const AVAILABLE_FUNCTIONS: &str =
    "\nSee a list of implemented functions using `names(parent())`\n";
```

2024-07-30 19:06 UTC, merged

2024-07-31 18:40 UTC, sebffischer commented
In rhai, they also offer a trait that can be implemented to support custom types: https://github.com/rhaiscript/rhai/blob/614f8f004be0509902d2a80fc5b85e16cc6aeac7/src/types/dynamic.rs#L98

2024-07-31 18:43 UTC, sebffischer commented
And this method here might also be handy to implement for `Obj`: https://github.com/rhaiscript/rhai/blob/614f8f004be0509902d2a80fc5b85e16cc6aeac7/src/types/dynamic.rs#L261

(sorry for abusing this PR for my notes)

2024-07-31 18:49 UTC, sebffischer commented
Another thing that might help for a cleaner solution to the problem that I am trying to solve here, would maybe be to support iterators as a `RepType`. Currently, casting an `Obj::Vector(Vector::Integer)` to a `Obj::Vector(Vector::Double)` is expensive, because it needs to allocate the double. But if we allow for `RepType::Iter`, we can directly implement the converson mechanism on `Obj`.